### ISSUE TITLE
Error while executing custom plugin

### ISSUE THREAD

**Issue by kameshbrao** [Kong/docker-kong-js-pdk#10]
Hi,

I'm creating a custom javascript plugin and trying a tutorial here -> https://konghq.com/blog/kong-gateway-plugin-javascript

So when using the plugin and starting the kong server I'm getting the below error. 

My Docker file is as follows

`FROM kong:latest

# Install the js-pluginserver
USER root
RUN apk add --update nodejs npm python3 make g++
RUN npm install --unsafe -g kong-pdk@0.5.3

ENV term xterm
RUN apk add --update vim nano`

and my docker-compose file is as follows

`version: "3.9"

services:
  kong:
    build: .
    user: "${KONG_USER:-kong}"
    volumes:
      - ./plugins:/usr/local/kong/js-plugins
      - ./config:/etc/kong/declarative
    environment:
      # Use the config defined in config/kong.yml
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/declarative/kong.yml
      # Show all output in the terminal when running with Docker
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      # Enable the JS plugin server
      KONG_PLUGINSERVER_NAMES: js
      KONG_PLUGINSERVER_JS_SOCKET: /usr/local/kong/js_pluginserver.sock
      KONG_PLUGINSERVER_JS_START_CMD: /usr/local/bin/kong-js-pluginserver -v --plugins-directory /usr/local/kong/js-plugins
      KONG_PLUGINSERVER_JS_QUERY_CMD: /usr/local/bin/kong-js-pluginserver --plugins-directory /usr/local/kong/js-plugins --dump-all-plugins
      # Allow plugins to be used. The plugin name is your JS file name e.g. hello.js
      KONG_PLUGINS: bundled, clacks
    ports:
      - "8000:8000/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
`

❯ docker-compose up
Starting docker-kong-js-pdk_kong_1 ... done
Attaching to docker-kong-js-pdk_kong_1
kong_1  | 2022/06/13 03:53:09 [warn] 1#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
kong_1  | nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
kong_1  | 2022/06/13 03:53:09 [error] 1#0: init_by_lua error: ...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:160: Not a plugin info table:
kong_1  | /usr/local/bin/kong-js-pluginserver --plugins-directory /usr/local/kong/js-plugins --dump-all-plugins
kong_1  | 2022-06-13T03:53:09.940Z [WARN] error loading plugin ".gitkeep" from /usr/local/kong/js-plugins/.gitkeep: TypeError: Cannot read properties of undefined (reading 'prototype')
kong_1  |     at new Module (/usr/local/lib/node_modules/kong-pdk/lib/mod.js:32:27)
kong_1  |     at Server.loadPlugins (/usr/local/lib/node_modules/kong-pdk/server.js:81:21)
kong_1  |     at new Server (/usr/local/lib/node_modules/kong-pdk/server.js:50:12)
kong_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/kong-pdk/bin/kong-js-pluginserver:18:12)
kong_1  |     at Module._compile (node:internal/modules/cjs/loader:1103:14)
kong_1  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
kong_1  |     at Module.load (node:internal/modules/cjs/loader:981:32)
kong_1  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
kong_1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
kong_1  |     at node:internal/main/run_main_module:17:47
kong_1  | [{"Name":"clacks","Version":"0.1.0","Phases":["access"],"Priority":0,"Schema":{"name":"clacks","fields":[{"config":{"type":"record","fields":[]}}]}}]
kong_1  |
kong_1  | stack traceback:
kong_1  | 	[C]: in function 'error'
kong_1  | 	...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:160: in function 'ask_info'
kong_1  | 	...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:197: in function 'get_plugin_info'
kong_1  | 	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:284: in function 'get_plugin'
kong_1  | 	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:292: in function 'load_plugin'
kong_1  | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:136: in function 'load_plugin_handler'
kong_1  | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:221: in function 'load_plugin'
kong_1  | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:273: in function 'load_plugin_schemas'
kong_1  | 	/usr/local/share/lua/5.1/kong/init.lua:543: in function 'init'
kong_1  | 	init_by_lua:3: in main chunk
kong_1  | nginx: [error] init_by_lua error: ...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:160: Not a plugin info table:
kong_1  | /usr/local/bin/kong-js-pluginserver --plugins-directory /usr/local/kong/js-plugins --dump-all-plugins
kong_1  | 2022-06-13T03:53:09.940Z [WARN] error loading plugin ".gitkeep" from /usr/local/kong/js-plugins/.gitkeep: TypeError: Cannot read properties of undefined (reading 'prototype')
kong_1  |     at new Module (/usr/local/lib/node_modules/kong-pdk/lib/mod.js:32:27)
kong_1  |     at Server.loadPlugins (/usr/local/lib/node_modules/kong-pdk/server.js:81:21)
kong_1  |     at new Server (/usr/local/lib/node_modules/kong-pdk/server.js:50:12)
kong_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/kong-pdk/bin/kong-js-pluginserver:18:12)
kong_1  |     at Module._compile (node:internal/modules/cjs/loader:1103:14)
kong_1  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
kong_1  |     at Module.load (node:internal/modules/cjs/loader:981:32)
kong_1  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
kong_1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
kong_1  |     at node:internal/main/run_main_module:17:47
kong_1  | [{"Name":"clacks","Version":"0.1.0","Phases":["access"],"Priority":0,"Schema":{"name":"clacks","fields":[{"config":{"type":"record","fields":[]}}]}}]
kong_1  |
kong_1  | stack traceback:
kong_1  | 	[C]: in function 'error'
kong_1  | 	...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:160: in function 'ask_info'
kong_1  | 	...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:197: in function 'get_plugin_info'
kong_1  | 	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:284: in function 'get_plugin'
kong_1  | 	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:292: in function 'load_plugin'
kong_1  | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:136: in function 'load_plugin_handler'
kong_1  | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:221: in function 'load_plugin'
kong_1  | 	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:273: in function 'load_plugin_schemas'
kong_1  | 	/usr/local/share/lua/5.1/kong/init.lua:543: in function 'init'
kong_1  | 	init_by_lua:3: in main chunk

Thanks for any help on this in adavance.

**Comment by rahul-plavelimana** [comment]
is this resolved? if yes please add the resolution steps
